void printASCII () {
	char Caractere[] = "☺";

	strcpy (Caractere, "☺");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "☻");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "♥");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "♦");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "♣");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "♠");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "♫");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "☼");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "►");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "◄");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "↕");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "‼");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¶");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "§");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▬");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "↨");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "↑");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "↓");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "→");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "←");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "∟");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "↔");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▲");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▼");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "!");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "\"");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "#");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "$");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "%");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "&");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "'");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "(");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ")");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "*");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "+");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ",");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "-");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ".");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "/");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "0");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "1");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "2");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "3");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "4");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "5");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "6");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "7");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "8");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "9");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ":");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ";");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "<");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "=");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, ">");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "?");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "@");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "A");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "B");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "C");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "D");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "E");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "F");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "G");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "H");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "I");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "J");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "K");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "L");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "M");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "N");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "O");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "P");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Q");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "R");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "S");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "T");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "U");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "V");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "W");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "X");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Y");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Z");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "[");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "\\");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "]");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "^");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "_");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "`");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "a");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "b");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "c");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "d");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "e");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "f");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "g");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "h");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "i");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "j");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "k");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "l");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "m");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "n");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "o");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "p");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "q");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "r");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "s");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "t");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "u");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "v");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "w");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "x");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "y");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "z");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "{");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "|");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "}");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "~");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "⌂");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ç");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ü");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "é");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "â");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ä");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "à");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "å");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ç");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ê");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ë");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "è");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ï");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "î");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ì");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ä");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Å");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "É");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "æ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Æ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ô");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ö");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ò");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "û");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ù");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ÿ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ö");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ü");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ø");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "£");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ø");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "×");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ƒ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "á");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "í");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ó");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ú");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ñ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ñ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ª");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "º");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¿");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "®");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¬");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "½");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¼");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¡");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "«");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "»");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "░");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▒");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▓");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "│");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┤");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Á");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Â");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "À");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "©");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╣");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "║");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╗");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╝");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¢");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¥");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┐");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "└");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┴");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┬");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "├");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "─");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┼");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ã");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ã");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╚");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╔");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╩");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╦");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╠");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "═");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "╬");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¤");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ð");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ð");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ê");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ë");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "È");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ı");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Í");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Î");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ï");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┘");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "┌");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "█");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▄");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¦");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ì");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "▀");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ó");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ß");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ô");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ò");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "õ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Õ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "µ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "þ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Þ");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ú");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Û");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ù");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "ý");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "Ý");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¯");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "´");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "­");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "±");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "‗");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¾");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¶");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "§");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "÷");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¸");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "°");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¨");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "·");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "¹");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "³");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "²");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
	strcpy (Caractere, "■");
	printf("%s = %d; %d; %d\t", Caractere, (unsigned char)Caractere[0], (unsigned char)Caractere[1], (unsigned char)Caractere[2]);
}
